@echo off
echo Closing current application...
taskkill /IM "MAX_PREMIUM_PRO_v1.0.1.exe" /F
timeout /t 2 /nobreak

echo Downloading new version...
powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/VannyLD/MAXPREMIUMPRO/releases/download/v1.0.1/MAX.PREMIUM.PRO.v1.0.2.exe', 'MAX_PREMIUM_PRO_v1.0.2.exe')"

echo Starting new version...
start MAX_PREMIUM_PRO_v1.0.2.exe

echo Cleaning up...
del "%~f0"
