@echo off
echo Closing current application...
taskkill /IM "MAX PREMIUM PRO v1.0.1.exe" /F
timeout /t 2 /nobreak

echo Downloading new version...
powershell -Command "(New-Object System.Net.WebClient).DownloadFile('https://github.com/VannyLD/AllinOneUpdate/releases/download/v1.7.4/All_in_One_V1.7.4.exe', 'All_in_One_v1.7.4.exe')"

echo Starting new version...
start MAX PREMIUM PRO v1.0.2.exe

echo Cleaning up...
del "%~f0"
